crud-laravel-master/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Import Model
use App\Mahasiswa;
use App\Dosen;
use App\Hobi;

// Route One to One
Route::get('relasi-1',function()
{
    // memilih data mahasiswa yg memiliki nim '101010101'
    $mhs = Mahasiswa::where('nim','=','101010101')->first();

    // Menampilkan data wali dari mahasiswa yang dipilih
    return $mhs->wali->nama;
});

Route::get('relasi-2',function()
{
    // memilih data mahasiswa yg memiliki nim '101010101'
    $mhs = Mahasiswa::where('nim','=','101010101')->first();
    // dd($mhs);
    // Menampilkan data dosen dari mahasiswa yang dipilih
    return $mhs->dosen->nama;
});

// One To Many
Route::get('relasi-3', function() {

    # Mencari dosen  yang bernama Abdul Musthafa
    $dosen = Dosen::where('nama', '=', 'Abdul Mustafa')->first();

    # Menampilkan data mahasiswa dari dosen yang dipilih
    foreach ($dosen->mahasiswa as $temp)
        echo '<li> Nama : ' . $temp->nama .
            ' <strong>' . $temp->nim . '</strong>
            </li>';
});

Route::get('relasi-4', function() {

    # Mencari mahasiswa yang bernama Dadang
    $dadang = Mahasiswa::where('nama', '=', 'Dadang')->first();

    # Menampilkan seluruh hobi dari Dadang
    foreach ($dadang->hobi as $temp)
        echo '<li>' . $temp->hobi . '</li>';
});

Route::get('relasi-5', function() {

    #  Mencari mahasasiswa yang bernama Dadang
    $dota = Hobi::where('hobi', '=', 'Dota 2')->first();
    // dd($dota);
    # Menampilkan semua mahasiswa yang mempunya hobi dota 2
    foreach ($dota->mahasiswa as $temp)
        echo '<li> Nama : ' . $temp->nama . ' <strong>' .
              $temp->nim . '</strong></li>';

});

Route::get('relasi-join', function() {

    // Join Laravel
    $sql = Mahasiswa::with('wali')->get();
    // $sql = DB::table('mahasiswas')
    // ->select('mahasiswas.nama','mahasiswas.nim',
    //          'walis.nama as nama_wali')
    // ->join('walis','walis.id_mahasiswa','=',
    //         'mahasiswas.id')
    // ->get();
    dd($sql);

});

Route::get('eloquent',function()
{
    $mahasiswa = Mahasiswa::with('wali','dosen','hobi')->get();
    // dd($mahasiswa);
    return view('eloquent',compact('mahasiswa'));
});

Route::get('latihan-eloquent',function()
{
    $mahasiswa = Mahasiswa::with('wali','dosen','hobi')
                    ->where('nama','=','Dadang')
                    ->first();
    // dd($mahasiswa);
    return view('eloquent2',compact('mahasiswa'));
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

// Blade Template
Route::get('beranda',function()
{
    return view('beranda');
});

Route::get('tentang',function()
{
    return view('tentang');
});

Route::get('kontak',function()
{
    return view('kontak');
});

// CRUD
Route::resource('dosen','DosenController');
Route::resource('hobi','HobiController');
Route::resource('mahasiswa','MahasiswaController');
Route::resource('wali','WaliController');

crud-laravel-master/app/Hobi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hobi extends Model
{
    public function mahasiswa()
    {
        return $this->belongsToMany('App\Mahasiswa',
                                    'mahasiswa_hobi',
                                    'id_hobi',
                                    'id_mahasiswa');
    }
}

crud-laravel-master/app/Http/Controllers/HobiController.php
<?php

namespace App\Http\Controllers;

use App\Hobi;
use Illuminate\Http\Request;

class HobiController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $hobi = Hobi::all();
        return view('hobi.index',compact('hobi'));
    }

    public function create()
    {
        return view('hobi.create');
    }

    public function store(Request $request)
    {
        $hobi = new Hobi();
        $hobi->hobi = $request->a;
        $hobi->save();
        return redirect()->route('hobi.index')
                ->with(['message'=>'Hobi berhasil dibuat']);
    }

    public function show($id)
    {
        $hobi =  Hobi::findOrFail($id);
        return view('hobi.show',compact('hobi'));

    }


    public function edit($id)
    {
        $hobi =  Hobi::findOrFail($id);
        return view('hobi.edit',compact('hobi'));
    }

    public function update(Request $request, $id)
    {
        $hobi = Hobi::findOrFail($id);
        $hobi->hobi = $request->a;
        $hobi->save();
        return redirect()->route('hobi.index')
                ->with(['message'=>'Hobi berhasil dibuat']);
    }

    public function destroy($id)
    {
       $hobi = Hobi::findOrFail($id)->delete();
        return redirect()->route('hobi.index')
                ->with(['message'=>'Hobi berhasil dibuat']);
    }
}

crud-laravel-master/resources/views/hobi/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Tambah Data hobi
                </div>
                <div class="card-body">
                    <form action="{{route('hobi.store')}}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="">Nama hobi</label>
                            <input type="text" name="nama" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

crud-laravel-master/resources/views/hobi/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Tambah Data hobi
                </div>
                <div class="card-body">
                    <form action="{{route('hobi.update',$hobi->id)}}" method="post">
                        <input type="hidden" nama="_method" value="PUT">
                        @method('PUT')
                        @csrf
                        <div class="form-group">
                            <label for="">Nama hobi</label>
                            <input type="text" name="a" value="{{$hobi->hobi}}" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

crud-laravel-master/resources/views/hobi/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            @if (session('message'))
                <div class="alert alert-success" role="alert">
                    {{ session('message') }}
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Data hobi
                    <a href="{{route('hobi.create')}}" class="float-right">
                        Tambah Data
                    </a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Nomor</th>
                                    <th>Hobi</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $no=1; @endphp
                                @foreach($hobi as $data)
                                <tr>
                                    <td>{{$no++}}</td>
                                    <td>{{$data->hobi}}</td>
                                    <td>
                                        <form action="{{route('hobi.destroy',$data->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{route('hobi.show',$data->id)}}" class="btn btn-sm btn-success">Lihat</a> |
                                            <a href="{{route('hobi.edit',$data->id)}}" class="btn btn-sm btn-warning">Edit</a> |
                                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Apakah Anda Yakin ?')">
                                                Hapus
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

crud-laravel-master/resources/views/hobi/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Lihat Data hobi
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="">Nama hobi</label>
                        <input type="text" name="a" value="{{$hobi->hobi}}" class="form-control" readonly>
                    </div>
                    <div class="form-group">
                        <a href="{{url()->previous()}}" class="btn btn-primary">Kembali</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection