crud-laravel-master/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Import Model
use App\Mahasiswa;
use App\Dosen;
use App\Hobi;

// Route One to One
Route::get('relasi-1',function()
{
    // memilih data mahasiswa yg memiliki nim '101010101'
    $mhs = Mahasiswa::where('nim','=','101010101')->first();

    // Menampilkan data wali dari mahasiswa yang dipilih
    return $mhs->wali->nama;
});

Route::get('relasi-2',function()
{
    // memilih data mahasiswa yg memiliki nim '101010101'
    $mhs = Mahasiswa::where('nim','=','101010101')->first();
    // dd($mhs);
    // Menampilkan data dosen dari mahasiswa yang dipilih
    return $mhs->dosen->nama;
});

// One To Many
Route::get('relasi-3', function() {

    # Mencari dosen  yang bernama Abdul Musthafa
    $dosen = Dosen::where('nama', '=', 'Abdul Mustafa')->first();

    # Menampilkan data mahasiswa dari dosen yang dipilih
    foreach ($dosen->mahasiswa as $temp)
        echo '<li> Nama : ' . $temp->nama .
            ' <strong>' . $temp->nim . '</strong>
            </li>';
});

Route::get('relasi-4', function() {

    # Mencari mahasiswa yang bernama Dadang
    $dadang = Mahasiswa::where('nama', '=', 'Dadang')->first();

    # Menampilkan seluruh hobi dari Dadang
    foreach ($dadang->hobi as $temp)
        echo '<li>' . $temp->hobi . '</li>';
});

Route::get('relasi-5', function() {

    #  Mencari mahasasiswa yang bernama Dadang
    $dota = Hobi::where('hobi', '=', 'Dota 2')->first();
    // dd($dota);
    # Menampilkan semua mahasiswa yang mempunya hobi dota 2
    foreach ($dota->mahasiswa as $temp)
        echo '<li> Nama : ' . $temp->nama . ' <strong>' .
              $temp->nim . '</strong></li>';

});

Route::get('relasi-join', function() {

    // Join Laravel
    $sql = Mahasiswa::with('wali')->get();
    // $sql = DB::table('mahasiswas')
    // ->select('mahasiswas.nama','mahasiswas.nim',
    //          'walis.nama as nama_wali')
    // ->join('walis','walis.id_mahasiswa','=',
    //         'mahasiswas.id')
    // ->get();
    dd($sql);

});

Route::get('eloquent',function()
{
    $mahasiswa = Mahasiswa::with('wali','dosen','hobi')->get();
    // dd($mahasiswa);
    return view('eloquent',compact('mahasiswa'));
});

Route::get('latihan-eloquent',function()
{
    $mahasiswa = Mahasiswa::with('wali','dosen','hobi')
                    ->where('nama','=','Dadang')
                    ->first();
    // dd($mahasiswa);
    return view('eloquent2',compact('mahasiswa'));
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

// Blade Template
Route::get('beranda',function()
{
    return view('beranda');
});

Route::get('tentang',function()
{
    return view('tentang');
});

Route::get('kontak',function()
{
    return view('kontak');
});

// CRUD
Route::resource('dosen','DosenController');
Route::resource('hobi','HobiController');
Route::resource('mahasiswa','MahasiswaController');
Route::resource('wali','WaliController');

crud-laravel-master/app/Mahasiswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mahasiswa extends Model
{
    public $fillable = ['nama','nim','id_dosen'];
    public $timestamps = true;

    public function dosen()
    {
        return $this->belongsTo('App\Dosen','id_dosen');
    }

    public function wali()
    {
        return $this->hasOne('App\Wali','id_mahasiswa');
    }

    public function hobi()
    {
        return $this->belongsToMany('App\Hobi',
                                    'mahasiswa_hobi',
                                    'id_mahasiswa',
                                    'id_hobi');
    }
}

crud-laravel-master/app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use App\Mahasiswa;
use Illuminate\Http\Request;
use App\Dosen;
use DB;
use App\Hobi;
class MahasiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $mhs = Mahasiswa::with('dosen')->get();
        // $mhs = DB::table('mahasiswas')
        // ->select('mahasiswas.*', 'dosens.nama as nama_dosen', 'dosens.nipd')
        // ->join('dosens', 'dosens.id', '=', 'mahasiswas.id_dosen')
        // ->get();
        // dd($mhs);
        return view('mahasiswa.index',compact('mhs'));
    }

    public function create()
    {
        $dosen = Dosen::all();
        $hobi = Hobi::all();
        return view('mahasiswa.create',compact('dosen','hobi'));
    }

    public function store(Request $request)
    {
        $mhs = new Mahasiswa();
        $mhs->nama = $request->nama;
        $mhs->nim = $request->nim;
        $mhs->id_dosen = $request->id_dosen;
        $mhs->save();
        $mhs->hobi()->attach($request->hobi);
        return redirect()->route('mahasiswa.index')
                ->with(['message'=>'Data berhasil dibuat']);
    }

    public function show($id)
    {
        $mhs = Mahasiswa::findOrFail($id);
        return view('mahasiswa.show',compact('mhs'));
    }

    public function edit($id)
    {
        $dosen = Dosen::all();
        $mhs = Mahasiswa::findOrFail($id);
        $select = $mhs->hobi->pluck('id')->toArray();
        $hobi = Hobi::all();
        // dd($select);
        return view('mahasiswa.edit',compact('mhs','hobi','dosen','select'));
    }


    public function update(Request $request, $id)
    {
        $mhs = Mahasiswa::findOrFail($id);
        $mhs->nama = $request->nama;
        $mhs->nim = $request->nim;
        $mhs->id_dosen = $request->id_dosen;
        $mhs->save();
        $mhs->hobi()->sync($request->hobi);
        return redirect()->route('mahasiswa.index')
                ->with(['message'=>'Data berhasil di edit']);
    }

    public function destroy($id)
    {
        $mhs = Mahasiswa::findOrFail($id);
        $mhs->hobi()->detach();
        $mhs->delete();
        return redirect()->route('mahasiswa.index')
                ->with(['message'=>'Data berhasil dihapus']);
    }
}

crud-laravel-master/resources/views/mahasiswa/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Tambah Data Mahasiswa
                </div>
                <div class="card-body">
                    <form action="{{route('mahasiswa.store')}}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="">Nama Mahasiswa</label>
                            <input type="text" name="nama" class="form-control" required>
                        </div>
                         <div class="form-group">
                            <label for="">NIM</label>
                            <input type="text" name="nim" class="form-control" required>
                        </div>
                         <div class="form-group">
                            <label for="">Nama Dosen</label>
                            {{-- <input type="text" name="id_dosen"> --}}
                            <select name="id_dosen" class="form-control" required>
                                @foreach($dosen as $data)
                                <option value="{{$data->id}}">{{$data->nama}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">Hobi</label>
                            <select class="form-control" id="js-multiple" name="hobi[]" multiple="multiple">
                                @foreach ($hobi as $data)
                                    <option value="{{$data->id}}">{{$data->hobi}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">
                                Simpan
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
    <script>
        $(document).ready(function() {
            $('#js-multiple').select2();
        });
    </script>
@endpush

crud-laravel-master/resources/views/mahasiswa/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Tambah Data Mahasiswa
                </div>
                <div class="card-body">
                    <form action="{{route('mahasiswa.update',$mhs->id)}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="">Nama Mahasiswa</label>
                            <input type="text" name="nama" value="{{$mhs->nama}}" class="form-control" required>
                        </div>
                         <div class="form-group">
                            <label for="">NIM</label>
                            <input type="text" name="nim" value="{{$mhs->nim}}" class="form-control" required>
                        </div>
                         <div class="form-group">
                            <label for="">Nama Dosen</label>
                            {{-- <input type="text" name="id_dosen"> --}}
                            <select name="id_dosen" class="form-control" required>
                                @foreach($dosen as $data)
                                <option value="{{$data->id}}"
                                    {{ $data->id == $mhs->id_dosen ? "selected" : "" }}>
                                    {{$data->nama}}
                                </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">Hobi</label>
                            <select class="js-multiple form-control" name="hobi[]" multiple="multiple">
                                @foreach ($hobi as $data)
                                    <option value="{{$data->id}}" {{ (in_array($data->id, $select)) ? 'selected' : '' }} >{{$data->hobi}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">
                                Simpan
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
    <script>
        $(document).ready(function() {
            $('.js-multiple').select2();
        });
    </script>
@endpush

crud-laravel-master/resources/views/mahasiswa/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            @if (session('message'))
                <div class="alert alert-success" role="alert">
                    {{ session('message') }}
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Data Mahasiswa
                    <a href="{{route('mahasiswa.create')}}" class="float-right">
                        Tambah Data
                    </a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Nomor</th>
                                    <th>Nama Mahasiswa</th>
                                    <th>Nomor Induk Sekolah</th>
                                    <th>Nama Dosen</th>
                                    <th>Hobi</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $no=1; @endphp
                                @foreach($mhs as $data)
                                <tr>
                                    <td>{{$no++}}</td>
                                    <td>{{$data->nama}}</td>
                                    <td>{{$data->nim}}</td>
                                    <td>{{$data->dosen->nama}}</td>
                                    <td>
                                        @foreach ($data->hobi as $item)
                                            <li>{{$item->hobi}}</li>
                                        @endforeach
                                    </td>
                                    <td>
                                        <form action="{{route('mahasiswa.destroy',$data->id)}}"  method="post">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{route('mahasiswa.show',$data->id)}}" class="btn btn-sm btn-success">Lihat</a> |
                                            <a href="{{route('mahasiswa.edit',$data->id)}}" class="btn btn-sm btn-warning">Edit</a> |
                                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Apakah Anda Yakin ?')">
                                                Hapus
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

crud-laravel-master/resources/views/mahasiswa/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Tambah Data Mahasiswa
                </div>
                <div class="card-body">
                    <form action="{{route('mahasiswa.update',$mhs->id)}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="">Nama Mahasiswa</label>
                            <input type="text" name="nama" value="{{$mhs->nama}}" class="form-control" readonly>
                        </div>
                         <div class="form-group">
                            <label for="">NIM</label>
                            <input type="text" name="nim" value="{{$mhs->nim}}" class="form-control" readonly>
                        </div>
                        <div class="form-group">
                            <label for="">Nama Dosen</label>
                            <input type="text" name="nim" value="{{$mhs->dosen->nama}}" class="form-control" readonly>
                        </div>
                        <div class="form-group">
                            <label for="">Daftar Hobi</label>
                            @foreach ($mhs->hobi as $item)
                                <li>{{$item->hobi}}</li>
                            @endforeach
                        </div>
                        <div class="form-group">
                            <a href="{{url()->previous()}}" class="btn btn-primary btn-block">
                                Kembali
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection