crud-laravel-master/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Import Model
use App\Mahasiswa;
use App\Dosen;
use App\Hobi;

// Route One to One
Route::get('relasi-1',function()
{
    // memilih data mahasiswa yg memiliki nim '101010101'
    $mhs = Mahasiswa::where('nim','=','101010101')->first();

    // Menampilkan data wali dari mahasiswa yang dipilih
    return $mhs->wali->nama;
});

Route::get('relasi-2',function()
{
    // memilih data mahasiswa yg memiliki nim '101010101'
    $mhs = Mahasiswa::where('nim','=','101010101')->first();
    // dd($mhs);
    // Menampilkan data dosen dari mahasiswa yang dipilih
    return $mhs->dosen->nama;
});

// One To Many
Route::get('relasi-3', function() {

    # Mencari dosen  yang bernama Abdul Musthafa
    $dosen = Dosen::where('nama', '=', 'Abdul Mustafa')->first();

    # Menampilkan data mahasiswa dari dosen yang dipilih
    foreach ($dosen->mahasiswa as $temp)
        echo '<li> Nama : ' . $temp->nama .
            ' <strong>' . $temp->nim . '</strong>
            </li>';
});

Route::get('relasi-4', function() {

    # Mencari mahasiswa yang bernama Dadang
    $dadang = Mahasiswa::where('nama', '=', 'Dadang')->first();

    # Menampilkan seluruh hobi dari Dadang
    foreach ($dadang->hobi as $temp)
        echo '<li>' . $temp->hobi . '</li>';
});

Route::get('relasi-5', function() {

    #  Mencari mahasasiswa yang bernama Dadang
    $dota = Hobi::where('hobi', '=', 'Dota 2')->first();
    // dd($dota);
    # Menampilkan semua mahasiswa yang mempunya hobi dota 2
    foreach ($dota->mahasiswa as $temp)
        echo '<li> Nama : ' . $temp->nama . ' <strong>' .
              $temp->nim . '</strong></li>';

});

Route::get('relasi-join', function() {

    // Join Laravel
    $sql = Mahasiswa::with('wali')->get();
    // $sql = DB::table('mahasiswas')
    // ->select('mahasiswas.nama','mahasiswas.nim',
    //          'walis.nama as nama_wali')
    // ->join('walis','walis.id_mahasiswa','=',
    //         'mahasiswas.id')
    // ->get();
    dd($sql);

});

Route::get('eloquent',function()
{
    $mahasiswa = Mahasiswa::with('wali','dosen','hobi')->get();
    // dd($mahasiswa);
    return view('eloquent',compact('mahasiswa'));
});

Route::get('latihan-eloquent',function()
{
    $mahasiswa = Mahasiswa::with('wali','dosen','hobi')
                    ->where('nama','=','Dadang')
                    ->first();
    // dd($mahasiswa);
    return view('eloquent2',compact('mahasiswa'));
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

// Blade Template
Route::get('beranda',function()
{
    return view('beranda');
});

Route::get('tentang',function()
{
    return view('tentang');
});

Route::get('kontak',function()
{
    return view('kontak');
});

// CRUD
Route::resource('dosen','DosenController');
Route::resource('hobi','HobiController');
Route::resource('mahasiswa','MahasiswaController');
Route::resource('wali','WaliController');

crud-laravel-master/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('select2/dist/js/select2.min.js') }}"></script>
    @stack('scripts')
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{asset('select2/dist/css/select2.min.css')}}" rel="stylesheet" />
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @guest
                        @else
                            <li class="nav-item">
                                <a href="{{route('wali.index')}}"
                                class="nav-link  {{ (request()->is('wali*')) ? 'active' : '' }}">
                                    Wali
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('dosen.index')}}"
                                class="nav-link  {{ (request()->is('dosen*')) ? 'active' : '' }}">
                                    Dosen
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('mahasiswa.index')}}"
                                class="nav-link {{ (request()->is('mahasiswa*')) ? 'active' : '' }}">
                                    Mahasiswa
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{route('hobi.index')}}"
                                class="nav-link {{ (request()->is('hobi*')) ? 'active' : '' }}">
                                    Hobi
                                </a>
                            </li>
                        @endguest
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>