crud-laravel-master/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Import Model
use App\Mahasiswa;
use App\Dosen;
use App\Hobi;

// Route One to One
Route::get('relasi-1',function()
{
    // memilih data mahasiswa yg memiliki nim '101010101'
    $mhs = Mahasiswa::where('nim','=','101010101')->first();

    // Menampilkan data wali dari mahasiswa yang dipilih
    return $mhs->wali->nama;
});

Route::get('relasi-2',function()
{
    // memilih data mahasiswa yg memiliki nim '101010101'
    $mhs = Mahasiswa::where('nim','=','101010101')->first();
    // dd($mhs);
    // Menampilkan data dosen dari mahasiswa yang dipilih
    return $mhs->dosen->nama;
});

// One To Many
Route::get('relasi-3', function() {

    # Mencari dosen  yang bernama Abdul Musthafa
    $dosen = Dosen::where('nama', '=', 'Abdul Mustafa')->first();

    # Menampilkan data mahasiswa dari dosen yang dipilih
    foreach ($dosen->mahasiswa as $temp)
        echo '<li> Nama : ' . $temp->nama .
            ' <strong>' . $temp->nim . '</strong>
            </li>';
});

Route::get('relasi-4', function() {

    # Mencari mahasiswa yang bernama Dadang
    $dadang = Mahasiswa::where('nama', '=', 'Dadang')->first();

    # Menampilkan seluruh hobi dari Dadang
    foreach ($dadang->hobi as $temp)
        echo '<li>' . $temp->hobi . '</li>';
});

Route::get('relasi-5', function() {

    #  Mencari mahasasiswa yang bernama Dadang
    $dota = Hobi::where('hobi', '=', 'Dota 2')->first();
    // dd($dota);
    # Menampilkan semua mahasiswa yang mempunya hobi dota 2
    foreach ($dota->mahasiswa as $temp)
        echo '<li> Nama : ' . $temp->nama . ' <strong>' .
              $temp->nim . '</strong></li>';

});

Route::get('relasi-join', function() {

    // Join Laravel
    $sql = Mahasiswa::with('wali')->get();
    // $sql = DB::table('mahasiswas')
    // ->select('mahasiswas.nama','mahasiswas.nim',
    //          'walis.nama as nama_wali')
    // ->join('walis','walis.id_mahasiswa','=',
    //         'mahasiswas.id')
    // ->get();
    dd($sql);

});

Route::get('eloquent',function()
{
    $mahasiswa = Mahasiswa::with('wali','dosen','hobi')->get();
    // dd($mahasiswa);
    return view('eloquent',compact('mahasiswa'));
});

Route::get('latihan-eloquent',function()
{
    $mahasiswa = Mahasiswa::with('wali','dosen','hobi')
                    ->where('nama','=','Dadang')
                    ->first();
    // dd($mahasiswa);
    return view('eloquent2',compact('mahasiswa'));
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

// Blade Template
Route::get('beranda',function()
{
    return view('beranda');
});

Route::get('tentang',function()
{
    return view('tentang');
});

Route::get('kontak',function()
{
    return view('kontak');
});

// CRUD
Route::resource('dosen','DosenController');
Route::resource('hobi','HobiController');
Route::resource('mahasiswa','MahasiswaController');
Route::resource('wali','WaliController');

crud-laravel-master/app/Wali.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wali extends Model
{
    public function mahasiswa()
    {
        return $this->belongsTo('App\Mahasiswa','id_mahasiswa');
    }
}

crud-laravel-master/app/Http/Controllers/WaliController.php
<?php

namespace App\Http\Controllers;

use App\Wali;
use Illuminate\Http\Request;
use App\Mahasiswa;
class WaliController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $wali = Wali::with('mahasiswa')->get();
        return view('wali.index',compact('wali'));
    }


    public function create()
    {
        $mhs = Mahasiswa::all();
        return view('wali.create',compact('mhs'));
    }


    public function store(Request $request)
    {
        $wali = new Wali();
        $wali->nama = $request->nama;
        $wali->id_mahasiswa = $request->id_mahasiswa;
        $wali->save();
        return redirect()->route('wali.index')->with(['message'=>'Data berhasil dibuat']);
    }

    public function show($id)
    {
        $wali = Wali::findOrFail($id);
        return view('wali.show',compact('wali'));
    }

    public function edit($id)
    {
        $mhs = Mahasiswa::all();
        $wali = Wali::findOrFail($id);
        return view('wali.edit',compact('mhs','wali'));
    }

    public function update(Request $request, $id)
    {

        $wali = Wali::findOrFail($id);
        $wali->nama = $request->nama;
        $wali->id_mahasiswa = $request->id_mahasiswa;
        $wali->save();
        return redirect()->route('wali.index')->with(['message'=>'Data berhasil diedit']);
    }

    public function destroy($id)
    {
        $wali = Wali::findOrFail($id)->delete();
        return redirect()->route('wali.index')->with(['message'=>'Data berhasil diedit']);
    }
}

crud-laravel-master/resources/views/wali/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Tambah Data Wali
                </div>
                <div class="card-body">
                    <form action="{{route('wali.store')}}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="">Nama Wali</label>
                            <input type="text" name="nama" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="">Nama Mahasiswa</label>
                            {{-- <input type="text" name="id_mahasiswa"> --}}
                            <select name="id_mahasiswa" class="form-control" required>
                                @foreach($mhs as $data)
                                <option value="{{$data->id}}">{{$data->nama}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">
                                Simpan
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

crud-laravel-master/resources/views/wali/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Edit Data Wali
                </div>
                <div class="card-body">
                    <form action="{{route('wali.update',$wali->id)}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="">Nama Wali</label>
                            <input type="text" name="nama" value="{{$wali->nama}}" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="">Nama Mahasiswa</label>
                            <select name="id_mahasiswa" class="form-control" required>
                                @foreach($mhs as $data)
                                <option value="{{$data->id}}"
                                    {{ $data->id == $wali->id_mahasiswa ? "selected" : "" }}>
                                    {{$data->nama}}
                                </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">
                                Simpan
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

crud-laravel-master/resources/views/wali/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            @if (session('message'))
                <div class="alert alert-success" role="alert">
                    {{ session('message') }}
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    Data Wali
                    <a href="{{route('wali.create')}}" class="float-right">
                        Tambah Data
                    </a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Nomor</th>
                                    <th>Nama Wali</th>
                                    <th>Nama Mahasiswa</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $no=1; @endphp
                                @foreach($wali as $data)
                                <tr>
                                    <td>{{$no++}}</td>
                                    <td>{{$data->nama}}</td>
                                    <td>{{$data->mahasiswa->nama}}</td>
                                    <td>
                                        <form action="{{route('wali.destroy',$data->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{route('wali.show',$data->id)}}" class="btn btn-sm btn-success">Lihat</a> |
                                            <a href="{{route('wali.edit',$data->id)}}" class="btn btn-sm btn-info">Edit</a> |
                                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Apakah Anda Yakin ?')">
                                                Hapus
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

crud-laravel-master/resources/views/wali/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    Edit Data Wali
                </div>
                <div class="card-body">
                    <form action="{{route('wali.update',$wali->id)}}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="">Nama Wali</label>
                            <input type="text" name="nama" value="{{$wali->nama}}" class="form-control" readonly>
                        </div>
                        <div class="form-group">
                            <label for="">Nama Mahasiswa</label>
                             <input type="text" name="nama" value="{{$wali->nama}}" class="form-control" readonly>
                        </div>
                        <div class="form-group">
                            <a href="{{url()->previous()}}" class="btn btn-primary btn-block">
                                Kembali
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection